server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 47.114.45.155
      port: 8500
      discovery:
        service-name: ${spring.application.name}