server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cczyWyc/springcloud-config.git
          # 搜索目录
          search-paths:
            - springcloud-config
          # 读取分支
      label: master
  rabbitmq:
    host: 47.114.45.155
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbit相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
